import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import type { ReactNode } from "react";
import type { Metadata } from "next";
import Header from "@/components/Headers";
import Footer from "@/components/Footers";
import { Providers } from "./provider";
import { CartProvider } from "@/context/CartonText";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-900 text-white min-h-screen`}
      >
        <Providers>
          <CartProvider>
            <Header />
            {children}
            <Toaster />
            <Footer />
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
